apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/dragoonsbets/drg-ms-bet:{{.VERSION}}"
  artifacts:
  - imageName: drg-ms-bet
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/dragoonsbets/drg-ms-bet:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: drg-ms-bet
        chartPath: charts/drg-ms-bet
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/dragoonsbets/drg-ms-bet"
          image.tag: "{{.DIGEST_HEX}}"